[package]
name = "wasi_vercel_example"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

[[bin]]
name = "grayscale"
path = "src/main.rs"

[dependencies]
hex = "0.4"
image = { version = "0.23.0", default-features = false, features = ["jpeg", "png", "gif"] }

